package Controleur;

import Modules.Livre;
import Utiles.PopUpForm;
import View.LivreView.LivreView;

import java.util.ArrayList;

public class GestionLivreView {
    private String[] addFields = {"Titre", "ID Auteur"}; // Updated field names
    private LivreView livreView;
    private ArrayList<Livre> livreList;
    private GestionLivre gestionLivre = new GestionLivre();

    public GestionLivreView() {
        this.livreList = getLivreList();
        this.livreView = new LivreView(livreList);
        initfunctions();
    }

    private void initfunctions() {
        addButton();
    }

    public LivreView getLivreView() {
        return livreView;
    }

    private ArrayList<Livre> getLivreList() {
        return gestionLivre.readAllLivres();
    }

    private void addButton() {
        livreView.getAddButton().addActionListener(e -> {
            // Create a new PopUpForm for adding a book
            PopUpForm<Livre> addForm = new PopUpForm<>(
                    "Ajouter un Livre",
                    addFields,
                    data -> {
                        // Parse the form data into a temporary Livre object
                        String titre = data.get("Titre");
                        int idAuteur = Integer.parseInt(data.get("ID Auteur"));

                        // Create a temporary Livre object with ID = 0 (auto-generated by the database)
                        return new Livre(0, titre, idAuteur);
                    }
            );

            // Add action listener to the "Enregistrer" button
            addForm.getSaveButton().addActionListener(ev -> {
                // Get the created Livre object from the form
                Livre newLivre = addForm.getObject();

                // Call the createLivre method to save the new book to the database
                gestionLivre.createLivre(newLivre.getTitre(), newLivre.getId_auteur());

                // Optionally refresh the table view to reflect the changes
                livreView.populateTable(gestionLivre.readAllLivres());
            });

            // Show the form dialog
            addForm.setVisible(true);
        });
    }
}